import { BlogStructure } from './blogStructure'

export const BLOGS : BlogStructure[] 
= [ 
	{ id: 0, title: 'Angular Setup', body: 'Angular Setup body Angular Setup body Angular Setup body Angular Setup body Angular Setup body Angular Setup body Angular Setup body Angular Setup bodyAngular Setup body Angular Setup body Angular Setup body Angular Setup bodyAngular Setup body Angular Setup body Angular Setup body Angular Setup bodyAngular Setup body Angular Setup body Angular Setup body Angular Setup bodyAngular Setup body Angular Setup body Angular Setup body Angular Setup bodyAngular Setup body Angular Setup body Angular Setup body Angular Setup bodyAngular Setup body Angular Setup body Angular Setup body Angular Setup bodyAngular Setup body Angular Setup body Angular Setup body Angular Setup bodyAngular Setup body Angular Setup body Angular Setup body Angular Setup bodyAngular Setup body Angular Setup body Angular Setup body Angular Setup bodyAngular Setup body Angular Setup body Angular Setup body Angular Setup bodyAngular Setup body Angular Setup body Angular Setup body Angular Setup bodyAngular Setup body Angular Setup body Angular Setup body Angular Setup bodyAngular Setup body Angular Setup body Angular Setup body Angular Setup bodyAngular Setup body Angular Setup body Angular Setup body Angular Setup bodyAngular Setup body Angular Setup body Angular Setup body Angular Setup bodyAngular Setup body Angular Setup body Angular Setup body Angular Setup bodyAngular Setup body Angular Setup body Angular Setup body Angular Setup body'
                                          , creationDate: '11/04/1919, 10:50:18', modificationDate: '19-Mar-2020', category: 'Studies', show: true }, 



	{ id: 1, title: 'Kadhi recipe',  body: ' Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows ', creationDate: '11/04/1820, 10:50:18', modificationDate: '14-Mar-2020', category: 'Food', show: true}, 
  
	{ id: 2, title: 'Nodejs Setup', body: ' Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body  Nodejs Setup body ', creationDate: '11/04/1919, 10:50:18', modificationDate: '19-Mar-2020', category: 'Studies', show: true }, 

	{ id: 3, title: 'Dal recipe',  body: ' Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows  Ingredients: As follows ', creationDate: '11/04/1820, 10:50:18', modificationDate: '14-Mar-2020', category: 'Food', show: true} 
  ]

